### ISSUE TITLE
run tests and create a github "check" for PRs against the main branch

### ISSUE THREAD

**Issue by rlmcneary2** [bitovi/react-numerics#10]
Tests need to be run when a PR is created against the main branch (or any PR?). If the tests fail the PR cannot be merged to main - github "check" on main branch.

Mick posted "Create workflows that enable you to use Continuous Integration (CI) for your projects."
https://github.com/skills/continuous-integration

**Comment by mickmcgrath13** [comment]
@rlmcneary2 How do the tests run?  is it just `npm run test` ?

**Comment by mickmcgrath13** [comment]
also, this requires a branch protection rule to require status checks to pass before merging:
![image](https://user-images.githubusercontent.com/1030325/174848957-63230f81-4ae7-455e-aefd-dc37f23f67d3.png)

**Comment by mickmcgrath13** [comment]
@rlmcneary2 I updated the necessary branch protection rule, so merging that PR should be all that remains on this ticket

**Comment by mickmcgrath13** [comment]
also, the check already ran for this branch :)
https://github.com/bitovi/react-numerics/actions/runs/2536843799

![image](https://user-images.githubusercontent.com/1030325/174850686-8a001073-036e-4d99-bee9-3733b068380a.png)
