### ISSUE TITLE
github action to automate build & publish of the package

### ISSUE THREAD

**Issue by rlmcneary2** [bitovi/react-numerics#8]
It would be great if there was an action that accomplished the "Publish" steps automatically (outlined in the root README). This action may be applicable to any NX workspace. A single NX workspace could have multiple publishable packages so the dep graph would need to be used to determine which packages to publish.

The publish action runs every time a merge to the main branch happens.

- Tests need to be run and pass before the merge can happen.
- How to handle different version bumps that might be needed (major, minor, bug fix, alpha/beta)?
- How to label alpha/beta/RC with the "next" tag? All other publishes are "latest?"

Mick posted "Create workflows that enable you to use Continuous Integration (CI) for your projects."
https://github.com/skills/continuous-integration

**Comment by mickmcgrath13** [comment]
@rlmcneary2 on these points:
> How to handle different version bumps that might be needed (major, minor, bug fix, alpha/beta)?
> How to label alpha/beta/RC with the "next" tag? All other publishes are "latest?"

One approach is to have every commit to the base branch just publish a `latest` and when you tag a release in github, another workflow runs to publish an artifact to match the github tag.  Will that resolve these two points?

**Comment by mickmcgrath13** [comment]
I added a secret to github actions for the npm publish called `NPM_TOKEN`

**Comment by ccapell** [comment]
### Option 1
- https://aboutbits.it/blog/2021-03-11-using-github-actions-to-perfom-npm-version-increment
- This handles patches
- For minor and Major versions the JSON would need to be manually updated
-- How do we keep .0 for these versions?
- Doesn't increment version for Next tags
- Can this be run when a new branch is created?
- What about Beta versions?
- Is it OK if we skip some patch numbers?  ie every build we bump

**Comment by rlmcneary2** [comment]
I think this works if branches are used to control versions. Kind of like this.

```txt
              patch bump     major bump (from next package.json)
--------------0--------------0-------> main
  |           ^              ^
  --> patch --|              |
  |                          |
  --> next 2.0.0 ------------|
```

**Comment by ccapell** [comment]
So the GitHub tags idea really won't work, at least not how you described it as working.  I'd want to add a tag to Git for any package that we push to NPM as latest, but a tag is created from a branch but no longer has one. 

So GIT is basically just a bunch of commits with a SHA.  Branches and tags are very similar in nature, in that they both are created from a commit.  The difference is that while a branch has the SHA pointer updated at every commit, a Tag is a point in time.

Below is a snip from a git log.  We can see the commit has both a tag and a branch at this point in time.  It is also the latest commit.

```
ccapell@bitovi-ccapell github-actions-docker-publish % git log
commit d05db56a355ea531da9915c2192cb6e2e191a972 (HEAD -> main, tag: v1, origin/main)
Author: Chris Capell <57496718+ccapell@users.noreply.github.com>
Date:   Fri Apr 22 14:23:48 2022 -0400
```
Scrolling through the log we can see a second tag.  
```
commit 479e8195716297f81677bfab96a77308cd0e692f (tag: v1.0.0)
Author: Chris Capell <57496718+ccapell@users.noreply.github.com>
Date:   Mon Apr 18 12:18:52 2022 -0400
```
This time we see the tag but notice we no longer have a branch.

**Comment by rlmcneary2** [comment]
@mickmcgrath13 I missed a lot of these and they may no longer be relevant but for completeness:

> are next tags associated with the previous version, or are they associated with a "version to come"?

"version to come"

v1.0.1@latest
v1.1.0-alpha1@next

**Comment by rlmcneary2** [comment]
> @rlmcneary2 (cc @ccapell), @christopherjbaker created this: https://github.com/bitovi/eslint-config/blob/main/.github/workflows/publish.yml
> 
> Would that logic be sufficient for `react-numerics` too?

👍

**Comment by ccapell** [comment]
@rlmcneary2  @mickmcgrath13 Can I get access to this repo so I can upload my workflow?

**Comment by rlmcneary2** [comment]
@ccapell @mickmcgrath13 Is there a specific team I should give access to? There's an open source team that I added but it only has two members.

**Comment by rlmcneary2** [comment]
@ccapell I added the bitovi organization so you should be all set now.

**Comment by ccapell** [comment]
PR #22  was merged with the new workflow
